language: python
services:
  - docker
python:
  - '3.6'
script:
  - 'docker build -t ${TRAVIS_REPO_SLUG} .'
  - 'docker tag ${TRAVIS_REPO_SLUG} device-manager'
  - 'cd tests'
  - 'docker build -t dredd-device-manager .'
  - 'docker-compose up -d kafka data-broker postgres'
  - 'docker-compose up device-manager'
after_success:
  - travis/publish.sh
