language: python
services:
  - docker
python:
  - '3.6'
script:
  - 'docker build -t dojot/device-manager .'
  - 'docker build -t dredd/base -f tests/dredd.dockerfile .'
  - 'docker build -t dredd/test -f tests/tests.dockerfile .'
  - 'docker-compose -p test -f tests/docker-compose.yaml up -d kafka data-broker postgres device-manager'
  - 'docker-compose -p test -f tests/docker-compose.yaml run --rm test-runner'
after_success:
  - travis/publish.sh
